name: wecode-science
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - numpy
  - pandas
  - matplotlib
  - autoviz
  - transformers
  - pytorch-cuda
  - torchvision
  - pip
  - pip:
    - audiocraft
